# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90ef8d0021d6309c418a24172db920f59cb0ee35780d445fc5ceec297b280d4bb5ea053b6f54e96622c41dd217407e09a7cf7af85c84bf065b6282f8c7f489d1

test:
  secret_key_base: 9bcead1fedd2195f3dc92eda51ef9f03552950f0102c8f2104f4d4e0fd0e9119f94e16965c2a9fccb3b94688ff0a73afdcdbf16693e1a4e60254affc4246f989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
